// Prevents additional console window on Windows in release builds
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

mod p2p_core;

use p2p_core::P2PManager;
use std::sync::Mutex;
use tauri::State;

pub struct AppState {
    pub p2p_manager: Mutex<Option<P2PManager>>,
}

// Tauri IPC Command: Fetch the unique local peer ID generated by Rust Libp2p
#[tauri::command]
fn get_local_peer_id(state: State<'_, AppState>) -> Result<String, String> {
    let binding = state.p2p_manager.lock().map_err(|e| e.to_string())?;
    match &*binding {
        Some(manager) => Ok(manager.peer_id.to_string()),
        None => Err("P2P Manager not initialized".to_string()),
    }
}

// Tauri IPC Command: Send local Yjs CRDT changes down to the Rust Libp2p mesh network
#[tauri::command]
fn send_crdt_update(
    state: State<'_, AppState>,
    workspace_id: String,
    update_hex: String,
) -> Result<(), String> {
    let binding = state.p2p_manager.lock().map_err(|e| e.to_string())?;
    match &*binding {
        Some(manager) => {
            let msg = format!("{}:{}", workspace_id, update_hex);
            manager.tx.send(msg).map_err(|e| e.to_string())?;
            Ok(())
        }
        None => Err("P2P Manager is offline".to_string()),
    }
}

fn main() {
    tauri::Builder::default()
        .manage(AppState {
            p2p_manager: Mutex::new(None),
        })
        .setup(|app| {
            let window = app.get_window("main").unwrap();
            
            // Initialize Libp2p asynchronous network stack
            match P2PManager::new(window) {
                Ok(manager) => {
                    let state: State<'_, AppState> = app.state();
                    if let Ok(mut lock) = state.p2p_manager.lock() {
                        *lock = Some(manager);
                    }
                    println!("Tauri Rust backend successfully established P2P channels.");
                }
                Err(err) => {
                    eprintln!("Failed to bootstrap Rust native libp2p manager: {:?}", err);
                }
            }
            
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![get_local_peer_id, send_crdt_update])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
